yiisoft/user

src/User.php, tests/UserTest.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Improve user

src/User.php, tests/UserTest.php
| New feature?  |❌
| Fixed issues  | partially #3
=> Remove loginByAccessToken from User class

src/AutoLogin.php, src/AutoLoginIdentityInterface.php, tests/AutoLoginMiddlewareTest.php, tests/Support/AutoLoginIdentity.php, tests/Support/LastMessageLogger.php
=> Add autoLoginDuration

README.md, composer.json, config/params.php, config/web.php, psalm.xml, src/AutoLoginMiddleware.php, src/User.php, tests/AutoLoginMiddlewareTest.php
| New feature?  | ✔️
Need for make functionality "Remembe me" in app. When `addCookie` is false app should manually add cookie depending on user choise.
=> Add option "addCookie" for AutoLoginMiddleware

src/CurrentUser.php, tests/CurrentUserTest.php
=> Improve naming

config/web.php
Merge after https://github.com/yiisoft/factory/pull/78
=> Adopt configs to new factory syntax

config/web.php
=> Add state resetter

src/Login/Cookie/CookieLoginMiddleware.php, tests/Login/Cookie/CookieLoginMiddlewareTest.php
| Is bugfix?    | ✔️
| Fixed issues  | #38
=> Fix trigger of login events to CookieLoginMiddleware

src/Login/Cookie/CookieLogin.php, src/Login/Cookie/CookieLoginIdentityInterface.php, src/Login/Cookie/CookieLoginMiddleware.php, tests/Login/Cookie/CookieLoginMiddlewareTest.php, tests/Support/CookieLoginIdentity.php
=> Refactoring CookieLoginIdentityInterface methods

src/Login/Cookie/CookieLogin.php, src/Login/Cookie/CookieLoginMiddleware.php, tests/Login/Cookie/CookieLoginMiddlewareTest.php, tests/Login/Cookie/CookieLoginTest.php
| New feature?  | ✔️
| Fixed issues  | #37
=> Add expiration time storage to login cookie value

config/web.php, src/CurrentUser.php, tests/CurrentUserTest.php
It will be useful if the package will not be used with the `yiisoft/di` resetter.
=> Add clear() method to CurrentUser

src/CurrentUser.php, tests/CurrentUserTest.php, tests/Login/Cookie/CookieLoginMiddlewareTest.php, tests/UserAuthTest.php
=> Move session setup to setter and make config setters immutable in CurrentUser

composer.json, config/web.php, phpunit.xml.dist, psalm.xml, tests/ConfigTest.php
=> Add configuration tests

config/params.php, config/web.php, src/Login/Cookie/CookieLoginMiddleware.php, tests/ConfigTest.php, tests/Login/Cookie/CookieLoginMiddlewareTest.php
=> Fix force add cookie to response by flag

README.md, src/CurrentUser.php
=> Add usage description to readme

README.md, src/CurrentUser.php, src/UserAuth.php, tests/ConfigTest.php, tests/Login/Cookie/CookieLoginMiddlewareTest.php, tests/Login/LoginMiddlewareTest.php, tests/UserAuthTest.php
| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.
=> Separate chain calls

CHANGELOG.md, README.md, config/di-web.php, src/Login/Cookie/CookieLogin.php, src/Login/Cookie/CookieLoginMiddleware.php, tests/Login/Cookie/CookieLoginMiddlewareTest.php, tests/Login/Cookie/CookieLoginTest.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | #82
=> Fix #82: Make cookie duration nullable

.github/workflows/bc.yml, .github/workflows/build.yml, .github/workflows/composer-require-checker.yml, .github/workflows/mutation.yml, .github/workflows/rector.yml, .github/workflows/static.yml
=> Improve CI

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, composer.json
=> Add support for `psr/http-message` version `^2.0`

CHANGELOG.md, composer.json
=> Add support of `yiisoft/session` version `^3.0`
